
SELECT 
	CINEMA_SCHEDULE.CINEMA_NAME, MOVIE.MOVIE_NAME, CINEMA_SCHEDULE.SHOW_DATE , CINEMA_SCHEDULE.SHOW_TIME
FROM 
	MOVIE 
JOIN 
	(
		SELECT 
			CINEMA.CINEMA_NAME, SHOW_TIME.MOVIE_ID, DATE(SHOW_TIME.SHOW_DATE_TIME) as SHOW_DATE , DATE_FORMAT(SHOW_TIME.SHOW_DATE_TIME, "%H:%i") 
		AS 
			SHOW_TIME
		FROM 
			CINEMA
		JOIN 
			SHOW_TIME 
		ON 
			CINEMA.CINEMA_ID=SHOW_TIME.CINEMA_ID
		WHERE 
			CINEMA.CINEMA_NAME LIKE 'pvr'
		AND
			DATE(SHOW_TIME.SHOW_DATE_TIME) = '2024-03-28'
	) 
AS
	CINEMA_SCHEDULE
ON 
	MOVIE.MOVIE_ID=CINEMA_SCHEDULE.MOVIE_ID

ORDER BY SHOW_TIME;
