CREATE DATABASE BOOK_MY_SHOW;

USE BOOK_MY_SHOW;

CREATE TABLE CINEMA (
  CINEMA_ID int NOT NULL AUTO_INCREMENT,
  CINEMA_NAME varchar(50) NOT NULL,
  PRIMARY KEY (CINEMA_ID)
);


CREATE TABLE MOVIE (
  MOVIE_ID int NOT NULL AUTO_INCREMENT,
  MOVIE_NAME varchar(50) NOT NULL,
  PRIMARY KEY (MOVIE_ID)
);


CREATE TABLE SHOW_TIME (
  SHOW_TIME_ID int NOT NULL AUTO_INCREMENT,
  CINEMA_ID int DEFAULT NULL,
  MOVIE_ID int DEFAULT NULL,
  SHOW_DATE_TIME datetime DEFAULT NULL,
  PRIMARY KEY (SHOW_TIME_ID),
  FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA (CINEMA_ID),
  FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID)
);
